### ISSUE TITLE
Need Support: Got Freezing Camera 

### ISSUE THREAD

**Issue by binhtt6** [densen2014/BlazorMaui#4]
Hi, i try to build this project and got freezing camera ? when i keep touch the screen, video on camera can move
Could you support me for this case? w
THanks

https://user-images.githubusercontent.com/30441291/204958942-4c5eb7a8-cfa2-4d21-a62b-ee23ee64cbc5.mp4

**Comment by densen2014** [comment]
it is this project ? https://github.com/densen2014/BlazorMaui ? are you sure?

**Comment by binhtt6** [comment]
Sorry for comment wrong location :D
