### ISSUE TITLE
示例代码无法运行，是否要安装安全负载？

### ISSUE THREAD

**Issue by Bronts** [densen2014/BlazorMaui#6]
下载示例代码后，编译提示必须安装如android、ios等负载，如果只想运行wpf，应该如何设置呢？
![image](https://user-images.githubusercontent.com/3986255/209438675-5bccc38f-22f2-439c-b6f1-e732359a93c2.png)

**Comment by densen2014** [comment]
这个问题比较特殊加一下QQ群 645660665

**Comment by Bronts** [comment]
根据作者的指导，在项目配置文件中，将目标更改为只留下windows的即可。
`<TargetFramework>net7.0-windows</TargetFramework>`
