### ISSUE TITLE
能支持wifi扫描么？

### ISSUE THREAD

**Issue by qcjxberin** [densen2014/BlazorMaui#7]
能支持wifi扫描么？

**Comment by densen2014** [comment]
有什么思路吗？这么多个平台。

**Comment by qcjxberin** [comment]
目前没有啥思路，最近在研究，发现xamarin的一些扫码好像也存在问题

**Comment by densen2014** [comment]
xamarin就zxing或者安卓ios原生代码就行

**Comment by qcjxberin** [comment]
wifi扫描应该和zxing没有关系，这个是指扫描wifi可连接的列表

**Comment by densen2014** [comment]
> wifi扫描应该和zxing没有关系，这个是指扫描wifi可连接的列表

我以为你刚刚这条说的是扫条码。

wifi扫描你需要用到什么平台？

**Comment by qcjxberin** [comment]
主要还是安卓的
